### ISSUE TITLE
error with hmm write in checkm

### ISSUE THREAD

**Issue by ForrestBurt** [metagenome-atlas/atlas#216]
While trying to do a run of Atlas, I run into an error telling me that there are no input sequences to analyze after a host of other errors. Full log from where errors start is attached as atlas.log. Note the 

"Fatal exception (source file p7_hmmfile.c, line 2139):
hmm write failed
system error: No space left on device"

part at the very start. I can't find anything about an error like this out there. The log file it mentions at the end is attached as prodigal.log. The commands I run to get here are:

atlas init -d /path/to/databases /path/to/data
atlas run

I am running this out of a conda installation.

[atlas.log](https://github.com/metagenome-atlas/atlas/files/3351048/atlas.log)
[prodigal.log](https://github.com/metagenome-atlas/atlas/files/3351050/prodigal.log)

**Comment by SilasK** [comment]
No problem, the issue system is here for new issues.

I thought I resolved such an error in the last release 2.1.3 (also on conda). Which version are you using?

**Comment by ForrestBurt** [comment]
Conda version 4.7.5, Atlas version 2.1.3

**Comment by SilasK** [comment]
And the snakemake version?

**Comment by ForrestBurt** [comment]
Looks like 5.5.3

**Comment by SilasK** [comment]
Thank you @mdehollander for the analysis. Your issues are also relatd to this one, an bug in the use of snakemake checkpoints :-( 

For me, the problem was solved after #214 with snakemake version 4.5.4 . I don't know if a new bug was introduced in snakemake 4.5+ or if I missed something, I check that.

**Comment by SilasK** [comment]
There are definitively some bugs in snakemake. 
A solution that worked for me is to run 

`atlas run genomes "genomes/annotations/genes"  <other arguments>`

Could you check?

**Comment by mdehollander** [comment]
Which version of snakemake we should try? We did with `5.4.5` and `5.5.2`. You suggest `4.5.4` but atlas depend on snakemake >= 5.4.5: https://github.com/metagenome-atlas/atlas/blob/master/atlas/Snakefile#L23

**Comment by SilasK** [comment]
Sorry, I get confused, but I corrected my last post.

**Comment by mdehollander** [comment]
We are getting the same errors as in #217 with snakemake `5.4.5` and `5.5.2`. So I guess there is still something wrong, but is it in the snakefile/rules or in snakemake itself?

**Comment by ForrestBurt** [comment]
I'm testing that command with snakemake 5.5.2 right now, I'll edit this once I get the results.

**Comment by ForrestBurt** [comment]
Okay, so I still get the 

Fatal exception (source file p7_hmmfile.c, line 2139):
hmm write failed
system error: No space left on device

errors in my latest run with snakemake 5.4.5, but this time, the run seems to complete. I get the message "ATLAS finished" at the end, so I presume that's a good sign. Any insight into the above error and what it actually means, if anything?

**Comment by SilasK** [comment]
For the error with hmm write. 
It seems there is an error in checkm because it uses too much memory. This could impact the downstream process, e.g. dereplication.  This is probably related to the fact that you use 28 threads. I would set it to 8-12 *in the config file*. This is 8 for each job. atlas then runs as many jobs in parallel as your 28 cores allow. see docs for more detail

**Comment by mdehollander** [comment]
@SilasK Any idea how to solve the error we get with #217. We are still getting that.

**Comment by SilasK** [comment]
Did you tried: 

There are definitively some bugs in snakemake.
A solution that worked for me with snakemake v5.52 is to run

atlas run genomes "genomes/annotations/genes" <other arguments> 

Could you check?

**Comment by mdehollander** [comment]
We get the same error as in #217:
```
[Tue Jul  9 11:32:42 2019]

Error in rule get_genome_for_cat:

    jobid: 0

    output: genomes/taxonomy/MAG3/MAG3.fasta


RuleException:

IsADirectoryError in line 14 of ***/atlas_snakemake5.5.2/atlas/atlas/rules/cat_taxonomy.smk:

[Errno 21] Is a directory: 'genomes/genomes'

  File "***/atlas_snakemake5.5.2/atlas/atlas/rules/cat_taxonomy.smk", line 14, in __rule_get_genome_for_cat

  File "***/.conda/envs/atlas_sm5.5.2/lib/python3.6/shutil.py", line 241, in copy

  File "***/.conda/envs/atlas_sm5.5.2/lib/python3.6/shutil.py", line 120, in copyfile

  File "***/.conda/envs/atlas_sm5.5.2/lib/python3.6/concurrent/futures/thread.py", line 56, in run

Exiting because a job execution failed. Look above for error message
```

**Comment by ForrestBurt** [comment]
I've tried the ATLAS run with config settings as cores=28 mem=100, cores=8 mem=100, and cores=8 mem=32, and am still getting that hmm write failed error. Was that meant to be changed in the config.yaml that ATLAS creates or in a separate config file?

**Comment by SilasK** [comment]
@mdehollander can you try to remove (or better rename ) the '.snakemake' subdir in your working dir and the `genomes/genomes` folder. 

Try to rerun atlas with dry-run.

If atlas wants to redo many already performed steps, e.g. assembly you can first do `atlas run genomes --touch` this updates the timestamp of all the files. then you should run `atlas run genomes` and we'll see if now the checkpoint passes.

**Comment by ForrestBurt** [comment]
@SilasK Was that last message for me or @mdehollander ?

**Comment by SilasK** [comment]
So I tried to split the two issues in #217  and #216

@ForrestBurt 


The error message should be relatively clear:
```
"Fatal exception (source file p7_hmmfile.c, line 2139):
hmm write failed
system error: No space left on device"

```

Do you have a limitation of memory on your device? 
Do you run it on a server?

**Comment by ForrestBurt** [comment]
So after about two weeks worth of attempts to fix this, I'm still no closer. I've tried a lot of different memory configurations in config.yaml (high threads, high memory; low threads, high memory; low threads, low memory; etc) and even solved an unrelated threading issue along the way, but I'm still getting the hmm write failed error. I'm running this on a compute node with 250 GB of memory, and I'm still seeing failures even with settings like 6 threads and 10 GB of memory, which should never go over the cap. Any insight? Watching the job in htop shows that it never even comes close to the memory cap on the node.

**Comment by SilasK** [comment]
@ForrestBurt I'm sorry for your struggling. 
As I understood the error message, the problem is related to the disk space, not the ram memory. 
Can you check if you have constraints on the disk space you can use?

**Comment by ForrestBurt** [comment]
ulimit -a presents me with unlimited in relevant categories, and the file system that the run is being done from has functionally infinite (or at least functionally infinite for our purposes) memory.

**Comment by K2SOHIGH** [comment]
Hi @ForrestBurt and others, I am experiencing the same error as you (hmm write failed) while running checkM on a cluster, did you manage to resolve it?


Note that i'm not running Atlas workflow, just a little Snakefile to run checkM by batch.

**Comment by SilasK** [comment]
Sorry @K2SOHIGH I think I couldn't reproduce the error.
