### ISSUE TITLE
Test atlas

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#260]
Atlas can be tested in the folllowing example:

You need a working [conda package manager](https://docs.conda.io/en/latest/miniconda.html). 

# install atlas development version
```
git clone https://github.com/metagenome-atlas/atlas.git
cd atlas
conda env create -n atlasenv --file atlasenv.yml
conda activate atlasenv
pip install --editable .
```
 check if atlas works

```
atlas --help
.test/dryrun.sh
```
# Test atlas
## Get test data

Go somewhere you like to work and get test data
```
cd ~
git clone https://github.com/metagenome-atlas/example_data.git 
````

define a path for databases where you can store some 100gb
```
databases=./databases 
```

Create atlas project:

```
atlas init --db-dir $databases --working-dir testrun --interleaved-fastq example_data/reads/test
```

Inspect samples.tsv and config.yaml in testrun

### Dryrun 
```
atlas run all --working-dir testrun  --dryrun
```

### set up cluster integration

for slurm, lsf cluster systems. 
```
cookiecutter https://github.com/metagenome-atlas/clusterprofile.git -o ~/.config/snakemake
```
Dryrun with cluster
```
atlas run all --working-dir testrun --profile cluster --dryrun

```

### Run atlas
```
atlas run all --working-dir testrun --profile cluster
```

## test run locally

run ATLAS
```
atlas run all --working-dir testrun 
```

**Comment by David-Degnan** [comment]
Hello Silas, 

I'm running the test locally with ATLAS 2.2.1, Python 3.6.7, and CentOS Linux 7. I'm getting multiple errors (see below). I saw in another issue that 2.1.6 was a stable version, but haven't been able to find it anywhere. What version of ATLAS runs the best, and where is it located? 

Thank you for your time.

Sampling of errors (I can send log files if that's helpful): 
-NameError: name 'stylesheeet' is not defined
-ValueError: Invalid file path or buffer object type: <class 'NoneType'>
-Fatal error: exception Sys_error, no such file or directory
-IOError: [Errno 2] No such file or directory

**Comment by SilasK** [comment]
Thank you for testing atlas. 

The conda package should be stable? are you using it? 
At which stage of the above-explained procedure do you get the errors?

**Comment by David-Degnan** [comment]
I've used both the bioconda version (2.2.0) and the development version (2.2.1). The errors happen at step 6 of 54 with the "rule run_das_tool" which later triggers errors with the build assembly and qc reports. The logs/reports/QC_report.log is blank.

**Comment by SilasK** [comment]
Ok, so you can run atlas!

Can you send me the log file of the dastool rule? May me check also the input files for das tool. 

A frequent error is that there are no bins are predicted which make the pipeline fail.

**Comment by David-Degnan** [comment]
Here you go! :) 
[DASTool_Sample1.log](https://github.com/metagenome-atlas/atlas/files/3933442/DASTool_Sample1.log)
[DASTool_Sample1.log](https://github.com/metagenome-atlas/atlas/files/3933443/DASTool_Sample1.log)

**Comment by SilasK** [comment]
Everything ok. Can you please send me the snakemake log file. Mentioned in the stdout at the end. It's in the . snakemake/logs folder

**Comment by David-Degnan** [comment]
Here's the log file and then the output from the interactive session (not all the errors appear in the log file). 
[2019-12-05T174016.982877.snakemake.log](https://github.com/metagenome-atlas/atlas/files/3933629/2019-12-05T174016.982877.snakemake.log)
[2019-12-05T174016.982877.Errors.txt](https://github.com/metagenome-atlas/atlas/files/3933632/2019-12-05T174016.982877.Errors.txt)

**Comment by SilasK** [comment]
@David-Degnan 

stylesheeet error comes from [snakemake](https://github.com/snakemake/snakemake/pull/128) and will be resolved in a future release.

In the meantime, you can continue the atlas pipeline (skip the report jobs) by adding `-k`to the atlas command. 


The error in checkm:
``sh: line 1: 29535 Killed                  pplacer -j 1 -c 
```
might be due to not enough memory or too many threads
You specify to have 250BG ram, is this correct? 

maybe try to reduce the number of threads to pass this steps.

**Comment by David-Degnan** [comment]
I pulled the latest version and added the -k option, and the job failed (see log file). What was the last stable version of ATLAS to run the test files without errors? 

Thanks for the help!  
[2019-12-10T113145.302823.snakemake.log](https://github.com/metagenome-atlas/atlas/files/3947331/2019-12-10T113145.302823.snakemake.log)

**Comment by SilasK** [comment]
In the latest update #264, version 2.3, I solved the problem of the reports. 
The error in the checkm rule will however remain. 
The pplacer uses a lot of memory and I assume this leads to the error. 


I'm running the test data regularly, however on a cluster so memory is not an issue.

**Comment by David-Degnan** [comment]
I pulled the latest github version, updated the atlas environment with the yaml file, and then tried both atlas run all with and without the -k option. When I conda list metagenome-atlas, I still get version 2.2.1, but the git log shows I have your latest version. I'm getting 2 main errors which both times which lead to the run failing: 

- /usr/bin/bash: download_eggnog_data.py: command not found
- ModuleNotFoundError: No module named 'cufflinks'.

Conda list cufflinks shows that I have cufflinks version 2.2.1. Any advice?

**Comment by SilasK** [comment]
@David-Degnan I made a new release which fixes the error download_eggnog_data.py. 
I investigated the cufflinks error, but was not able to reproduce it. 
cufflink is used in the reports, but you don't need to install it your self. 

If it re-apears, coud you send me the log file of the step which produce the error (probably an report_qc or so).

**Comment by David-Degnan** [comment]
Thanks Silas! The previous errors have been fixed, but now there is an error with the gene2genome rule which causes ATLAS to stop running. I believe that's with the gtdb-tk step, so I've included that log file (which did have an error within it). 
[gtdbtk.log](https://github.com/metagenome-atlas/atlas/files/3957622/gtdbtk.log)

**Comment by SilasK** [comment]
Ok, gene2genome is the last rule of the whole pipeline. You came already far. 
If there is an error in gene2genome. the error is just put in the stdout. 

GTDBTK should be unrelated. But it's again a step that requires a lot of memory for phylogenetic placeement. :-(

**Comment by SilasK** [comment]
@David-Degnan, I made a new release, (soon on conda), which simplifies some of the environments, not that packages have to be installed several times. 
Could you try to restart the pipeline from the beginning (you can keep the databases)?

**Comment by SilasK** [comment]
@David-Degnan, I made a new release, (soon on conda), which simplifies some of the environments, not that packages have to be installed several times. 
Could you try to restart the pipeline from the beginning (you can keep the databases)?

Thank you for testing.

**Comment by David-Degnan** [comment]
To "restart", I should delete the testrun folder, but keep the databases, correct?

**Comment by David-Degnan** [comment]
Hello Silas, 
The atlas_test files contains the gene2genome errors, and the snakemake log file contains errors from a run I tried after deleting the testrun folder.
[2019-12-13T112923.956458.snakemake.log](https://github.com/metagenome-atlas/atlas/files/3962616/2019-12-13T112923.956458.snakemake.log)
[atlas_test.txt](https://github.com/metagenome-atlas/atlas/files/3962618/atlas_test.txt)
[atlas_test_err.txt](https://github.com/metagenome-atlas/atlas/files/3962624/atlas_test_err.txt)

**Comment by SilasK** [comment]
@David-Degnan  Thank, you very much. I found the bug in gene2genome.

No idea why there is an error in deduplcate?

Could you send me the `sample1/logs/QC/deduplicate.log`

Do you have access to a cluster system?  I yes could you also test to deploy atlas on a cluster, via the [following commands](https://metagenome-atlas.readthedocs.io/en/latest/usage/cluster.html)?

**Comment by SilasK** [comment]
@David-Degnan Could you manage to run atlas?

**Comment by David-Degnan** [comment]
@SilasK Not yet! The deduplicate issue was memory-related and has been fixed. Using the `atlas run all --working-dir testrun --profile cluster` always produces the error in atlas_test_err.txt
[atlas_test_err.txt](https://github.com/metagenome-atlas/atlas/files/4003556/atlas_test_err.txt), so I use `atlas test run all --working-dir testrun` which currently has an error with the metaSpades step 
[2019-12-26T142742.110943.snakemake.log](https://github.com/metagenome-atlas/atlas/files/4003566/2019-12-26T142742.110943.snakemake.log)
[spades_sample1.log](https://github.com/metagenome-atlas/atlas/files/4003568/spades_sample1.log)
[spades_sample2.log](https://github.com/metagenome-atlas/atlas/files/4003569/spades_sample2.log). I made sure to use the latest github version.

**Comment by SilasK** [comment]
For the cluster execution with `--profile cluster`:

Did you follow the instructions in this issue or wiht more details  in the [docs](https://metagenome-atlas.readthedocs.io/en/latest/usage/cluster.html)

This should produce a folder   `/home/degn400/.config/snakemake/cluster`. 

Spades error: 
metaspades needs a paired-end library. my test data is paired-end but in one file (interleaved). 
You can define this in the config.yaml file `interleaved_fastqs=true`. However if you encounter this error during the assembly, this means all the preprocessing was also done wrong (taking paired-end files as single end)..

The easiest is to restart the test, and use `atlas init --interleaved-fastq ` this sets the attribute correctly. I updated the docs with all the details for the test: https://metagenome-atlas.readthedocs.io/en/latest/usage/test.html

If you could test the cluster execution, this would be great, because this I cannot test with the docker. 
Thank you very much.

**Comment by David-Degnan** [comment]
Should I use your atlas_test.sh batch script from this repository? Will it fix the `interleaved_fastqs` in the .yaml file, or should that be fixed that manually?

**Comment by SilasK** [comment]
>Should I use your atlas_test.sh batch script from this repository?

I suggest togo step by step as described in the `https://metagenome-atlas.readthedocs.io/en/latest/usage/test.html` . But to simplify it I updated the  `atlas_test.sh` to reflect the latest changes. 

>Will it fix the interleaved_fastqs in the .yaml file, or should that be fixed that manually?

The easiest is to restart the test, and use `atlas init --interleaved-fastq` this sets the attribute correctly.

**Comment by SilasK** [comment]
Important is to use always the same database directory, even if you restart the test from the atlas init step. there is no nead of downloading databases (~100GB) again.

**Comment by David-Degnan** [comment]
Hello Silas! 
When I use the `--profile cluster` option, I still get the "yaml file not found" error.[atlas_test_err.txt](https://github.com/metagenome-atlas/atlas/files/4017758/atlas_test_err.txt) When running the pipeline, there's a hang up 95% of the way through with the eggnog step. 
[2020-01-02T115235.805928.snakemake.log](https://github.com/metagenome-atlas/atlas/files/4017773/2020-01-02T115235.805928.snakemake.log). It seems the problem is with missing GCF .fna files [gtdbtk.log](https://github.com/metagenome-atlas/atlas/files/4017791/gtdbtk.log). The fastani/database folder contains only GCA .fna files. Should I redownload the databases from conda and then update with the latest github version?

**Comment by SilasK** [comment]
Welcome back and happy New year.

The cluster problem:

If you follow the instructions on https://metagenome-atlas.readthedocs.io/en/latest/usage/cluster.html
You should get the requested  file in
`/home/degn400/.config/snakemake/cluster/config.yaml`

Eggnog error: 
Could you also send me the file : `Genecatalog/subsets/genes/logs/subset1/eggNOG_annotate_hits_table.log`

GTDB error: 

according to the log file the GTDB database was not completely downloaded:
can you remove 
`/dtemp/mscfcons/degnan/atlas_test/databases/GTDB-TK/`

and restart atlas again?

**Comment by David-Degnan** [comment]
Happy New Year! 
Thanks for clarifying which config.yaml file to use on cluster mode. I already had cookiecutter installed and have tried this instructions. Maybe using `atlas run -c path/to/config_file/  --profile cluster` would help? Unfortunately, I am low on time for this project so I won't be able to test it. Here's the file you asked for:[eggNOG_annotate_hits_table.log](https://github.com/metagenome-atlas/atlas/files/4020033/eggNOG_annotate_hits_table.log). When you say restart atlas, do you mean uninstall and reinstall from github again?

**Comment by SilasK** [comment]
No I ment judt rerun atlas. This will download the removed database again.

The eggnog error is related to a I/O error in sqlr3. No mich idea what could be the reason. Bit maybe also the database is not correctly download.

You should be able to seamlessly to install the latest version and continue. The latest version is on conda. And sice then I made only chanhes to the dockerfile which os not part of the source code.

Kind regards
Silas

**Comment by David-Degnan** [comment]
Hello Silas,
 
I scrapped ATLAS, reinstalled it, and redownloaded the databases. I got the same eggnog error. I'm afraid I can't test further at this time. But this does mean I have 95% of ATLAS working. 

Best of luck,
David

**Comment by SilasK** [comment]
Also the GTDB-tk error is the same?

**Comment by David-Degnan** [comment]
If you mean that no GCF databases appeared, then yes, it's the same. I only see GCA databases. Would it have something to do with a .yaml file?
